package com.FZBO.enums;

public enum EDisclosure {
    AGENT_OWNED,
    ASBESTOS,
    BUILDING_CONVERSION,
    CODE_COMPLIANCE_REQUIRED,
    DRAINAGE_ASSESSMENT,
    EASEMENT,
    MOLD,
    YEAR_BUILT_UNKNOWN,
    OCCUPANCY_PERMIT_REQUIRED,
    NONE
}
